default: &default
  adapter: oracle_enhanced
  encoding: unicode
  host: localhost
  username: sifd
  password: Adm1n5174*2024
  port: 1521
  database: XE
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  username: sifd
  password: <%= ENV['CORE_RAILS_DATABASE_PASSWORD'] %>
