default: &default
  adapter: oracle_enhanced
  # encoding: unicode
  encoding: utf8
  host: localhost
  port: 1521
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: sifd
  password: Adm1n5174*2024
  database: XE

test:
  <<: *default

production:
  <<: *default
  username: sifd
  password: <%= ENV['CORE_RAILS_DATABASE_PASSWORD'] %>
